name: C/C++ CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: get-cmake
      uses: lukka/get-cmake@v3.17.1
      with: 
        cmakeListsOrSettingsJson: CMakeListsTxtBasic
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
