name: C/C++ CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  ubuntu_build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: install packages
      run: sudo apt-get update -m && sudo apt-get install xorg-dev libglu1-mesa-dev libalut-dev
      shell: bash

    - name: get-cmake
      uses: lukka/run-cmake@v2.3
      with: 
        cmakeListsOrSettingsJson: CMakeListsTxtBasic
        configurationRegexFilter: 'Linux-Release'
        cmakeGenerator: 'Ninja'  
        buildWithCMakeArgs: '-- -v'
        buildDirectory: '${{ runner.workspace }}/b/ninja-bash/'
        useShell: bash
  
  mac_os_build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build mac executable
      uses: lukka/run-cmake@v2.3
      with:
        cmakeListsOrSettingsJson: CMakeListsTxtBasic
        configurationRegexFilter: 'mac-Release'
